name: Advanced Computing for Environmental Science
url: http://uor-aces.github.org

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: staff
    name: Research Staff
  - key: postdoc
    name: Researchers
  - key: grad
    name: Graduate Students
  - key: ugrad
    name: Undergraduate Students
  - key: ugrad-alum
    name: Past Undergraduate Students
  - key: collab
    name: Collaborators

footer_description: >
 Advanced Computing for Environmental  <br/>
 <a href="http://www.reading.ac.uk/smpcs-home.aspx">University of Reading - School of Mathematical, Physical and Computational Sciences </a>

# Number of news stories on the front page.
front_page_news: 6

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: Research
    link: /research.html
  - title: Publications
    link: /publications.html
  - title: Code
    link: /code.html
